### ISSUE TITLE
[Bug] RuneChanger always shows "not connected!" even when League is running.

### ISSUE THREAD

**Issue by mrhappyasthma** [stirante/RuneChanger#49]
I just unzip the program, ran `open.bat`. The program launches but never connects to the League client.

**Comment by stirante** [comment]
Could you check "Run as admin" in settings and try again? If you don't see this option, you might need to enable experimental channel.

**Comment by mrhappyasthma** [comment]
I did need to `enable experimental channel` before I could set `run as admin`.

But even after restarting and allowing as admin, I still see "not connected!".

I'm running on Windows 7, if that matters.

**Comment by stirante** [comment]
I pushed quick update to experimental channel. After updating, click `CTRL + L`. This will generate log, which should help me to find cause of the bug (this log may contain list of all running processes, so If you don't want to paste it here, you can send me directly at discord or mail me at brzozowski.s.piotr@gmail.com)

**Comment by mrhappyasthma** [comment]
```
Created at Thursday, July 2, 2020 at 11:28:14 AM Pacific Daylight Time
java.io.IOException: Cannot run program "WMIC": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:589)
	at java.base/java.lang.Runtime.exec(Runtime.java:413)
	at java.base/java.lang.Runtime.exec(Runtime.java:310)
	at com.stirante.lolclient.ClientApi.generateDebugLog(ClientApi.java:710)
	at com.stirante.runechanger.gui.Settings$2.doInBackground(Settings.java:238)
	at com.stirante.runechanger.gui.Settings$2.doInBackground(Settings.java:235)
	at com.stirante.runechanger.util.AsyncTask.lambda$execute$2(AsyncTask.java:12)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 13 more
```

**Comment by stirante** [comment]
Looks like you don't have wmic, which is weird. It is deprecated, but I still have it on windows 10. Do you have powershell on windows 7? I could write a new implementation of checking for the LCU process If that's the case.

**Comment by mrhappyasthma** [comment]
I did some debugging and was able to resolve this.

I needed to add `%SystemRoot%\System32\Wbem` to my Path environment variable. Then it was able to find `wmic`.
