### ISSUE TITLE
[Bug] Automatic update 1.14.1 to 1.14.2 fails

### ISSUE THREAD

**Issue by luk-lo** [stirante/RuneChanger#76]
**Describe the bug**
Automatic update to 1.14.2 fails.

**To Reproduce**
1. Open RuneChanger 1.14.1
2. Press "Yes" on the "Update available!" popup.
3. See errors in the cmd log, RuneChanger remains on 1.14.1

**Expected behavior**
The update completes without errors and RuneChanger version changes to 1.14.2

**Logs**
```
WARNING: Updating without signature validation is strongly discouraged.
icon.ico:  SYNCHRONIZED
image\bin\api-ms-win-core-console-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-datetime-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-debug-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-errorhandling-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-file-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-file-l1-2-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-file-l2-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-handle-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-heap-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-interlocked-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-libraryloader-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-localization-l1-2-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-memory-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-namedpipe-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-processenvironment-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-processthreads-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-processthreads-l1-1-1.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-profile-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-rtlsupport-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-string-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-synch-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-synch-l1-2-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-sysinfo-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-timezone-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-core-util-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-conio-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-convert-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-environment-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-filesystem-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-heap-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-locale-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-math-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-multibyte-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-private-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-process-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-runtime-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-stdio-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-string-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-time-l1-1-0.dll:  SYNCHRONIZED
image\bin\api-ms-win-crt-utility-l1-1-0.dll:  SYNCHRONIZED
image\bin\awt.dll:  UPDATE
image\bin\client\jvm.dll:  UPDATE
image\bin\decora_sse.dll:  SYNCHRONIZED
image\bin\fontmanager.dll:  UPDATE
image\bin\freetype.dll:  UPDATE
image\bin\glass.dll:  SYNCHRONIZED
image\bin\java.dll:  UPDATE
image\bin\java.exe:  UPDATE
image\bin\javafx_font.dll:  SYNCHRONIZED
image\bin\javafx_iio.dll:  SYNCHRONIZED
image\bin\javajpeg.dll:  UPDATE
image\bin\javaw.exe:  UPDATE
image\bin\jawt.dll:  UPDATE
image\bin\jimage.dll:  UPDATE
image\bin\jli.dll:  UPDATE
image\bin\jrunscript.exe:  UPDATE
image\bin\jsound.dll:  UPDATE
image\bin\keytool.exe:  UPDATE
image\bin\lcms.dll:  UPDATE
image\bin\mlib_image.dll:  UPDATE
image\bin\msvcp140.dll:  SYNCHRONIZED
image\bin\net.dll:  UPDATE
image\bin\nio.dll:  UPDATE
image\bin\prefs.dll:  UPDATE
image\bin\prism_common.dll:  SYNCHRONIZED
image\bin\prism_d3d.dll:  SYNCHRONIZED
image\bin\prism_sw.dll:  SYNCHRONIZED
image\bin\server\jvm.dll:  UPDATE
image\bin\splashscreen.dll:  UPDATE
image\bin\sunec.dll:  UPDATE
image\bin\ucrtbase.dll:  SYNCHRONIZED
image\bin\vcruntime140.dll:  SYNCHRONIZED
image\bin\verify.dll:  UPDATE
image\bin\zip.dll:  UPDATE
image\conf\logging.properties:  SYNCHRONIZED
image\conf\net.properties:  SYNCHRONIZED
image\conf\security\java.policy:  SYNCHRONIZED
image\conf\security\java.security:  UPDATE
image\conf\security\policy\limited\default_local.policy:  SYNCHRONIZED
image\conf\security\policy\limited\default_US_export.policy:  SYNCHRONIZED
image\conf\security\policy\limited\exempt_local.policy:  SYNCHRONIZED
image\conf\security\policy\README.txt:  SYNCHRONIZED
image\conf\security\policy\unlimited\default_local.policy:  SYNCHRONIZED
image\conf\security\policy\unlimited\default_US_export.policy:  SYNCHRONIZED
image\conf\sound.properties:  SYNCHRONIZED
image\legal\java.base\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.base\aes.md:  SYNCHRONIZED
image\legal\java.base\asm.md:  SYNCHRONIZED
image\legal\java.base\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.base\c-libutl.md:  SYNCHRONIZED
image\legal\java.base\cldr.md:  SYNCHRONIZED
image\legal\java.base\icu.md:  SYNCHRONIZED
image\legal\java.base\LICENSE:  SYNCHRONIZED
image\legal\java.base\public_suffix.md:  UPDATE
image\legal\java.base\unicode.md:  SYNCHRONIZED
image\legal\java.base\zlib.md:  SYNCHRONIZED
image\legal\java.datatransfer\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.datatransfer\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.datatransfer\LICENSE:  SYNCHRONIZED
image\legal\java.desktop\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.desktop\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.desktop\colorimaging.md:  SYNCHRONIZED
image\legal\java.desktop\freetype.md:  SYNCHRONIZED
image\legal\java.desktop\giflib.md:  UPDATE
image\legal\java.desktop\harfbuzz.md:  UPDATE
image\legal\java.desktop\jpeg.md:  SYNCHRONIZED
image\legal\java.desktop\lcms.md:  SYNCHRONIZED
image\legal\java.desktop\libpng.md:  SYNCHRONIZED
image\legal\java.desktop\LICENSE:  SYNCHRONIZED
image\legal\java.desktop\mesa3d.md:  SYNCHRONIZED
image\legal\java.desktop\opengl.md:  SYNCHRONIZED
image\legal\java.logging\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.logging\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.logging\LICENSE:  SYNCHRONIZED
image\legal\java.naming\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.naming\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.naming\LICENSE:  SYNCHRONIZED
image\legal\java.prefs\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.prefs\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.prefs\LICENSE:  SYNCHRONIZED
image\legal\java.scripting\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.scripting\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.scripting\LICENSE:  SYNCHRONIZED
image\legal\java.security.sasl\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.security.sasl\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.security.sasl\LICENSE:  SYNCHRONIZED
image\legal\java.sql\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.sql\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.sql\LICENSE:  SYNCHRONIZED
image\legal\java.transaction.xa\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.transaction.xa\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.transaction.xa\LICENSE:  SYNCHRONIZED
image\legal\java.xml\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\java.xml\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\java.xml\bcel.md:  SYNCHRONIZED
image\legal\java.xml\dom.md:  SYNCHRONIZED
image\legal\java.xml\jcup.md:  SYNCHRONIZED
image\legal\java.xml\LICENSE:  SYNCHRONIZED
image\legal\java.xml\xalan.md:  SYNCHRONIZED
image\legal\java.xml\xerces.md:  SYNCHRONIZED
image\legal\javafx.base\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\javafx.base\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\javafx.base\LICENSE:  SYNCHRONIZED
image\legal\javafx.controls\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\javafx.controls\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\javafx.controls\LICENSE:  SYNCHRONIZED
image\legal\javafx.fxml\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\javafx.fxml\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\javafx.fxml\LICENSE:  SYNCHRONIZED
image\legal\javafx.graphics\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\javafx.graphics\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\javafx.graphics\jpeg_fx.md:  SYNCHRONIZED
image\legal\javafx.graphics\LICENSE:  SYNCHRONIZED
image\legal\javafx.swing\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\javafx.swing\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\javafx.swing\LICENSE:  SYNCHRONIZED
image\legal\jdk.crypto.ec\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\jdk.crypto.ec\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\jdk.crypto.ec\ecc.md:  SYNCHRONIZED
image\legal\jdk.crypto.ec\LICENSE:  SYNCHRONIZED
image\legal\jdk.unsupported\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\jdk.unsupported\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\jdk.unsupported\LICENSE:  SYNCHRONIZED
image\legal\jdk.unsupported.desktop\ADDITIONAL_LICENSE_INFO:  SYNCHRONIZED
image\legal\jdk.unsupported.desktop\ASSEMBLY_EXCEPTION:  SYNCHRONIZED
image\legal\jdk.unsupported.desktop\LICENSE:  SYNCHRONIZED
image\lib\classlist:  UPDATE
image\lib\client\Xusage.txt:  UPDATE
image\lib\fontconfig.bfc:  SYNCHRONIZED
image\lib\fontconfig.properties.src:  SYNCHRONIZED
image\lib\javafx-swt.jar:  SYNCHRONIZED
image\lib\javafx.properties:  SYNCHRONIZED
image\lib\jawt.lib:  SYNCHRONIZED
image\lib\jrt-fs.jar:  UPDATE
image\lib\jvm.cfg:  UPDATE
image\lib\jvm.lib:  UPDATE
image\lib\modules:  UPDATE
image\lib\psfont.properties.ja:  SYNCHRONIZED
image\lib\psfontj2d.properties:  SYNCHRONIZED
image\lib\security\blacklisted.certs:  SYNCHRONIZED
image\lib\security\cacerts:  UPDATE
image\lib\security\default.policy:  SYNCHRONIZED
image\lib\security\public_suffix_list.dat:  UPDATE
image\lib\server\Xusage.txt:  SYNCHRONIZED
image\lib\tzdb.dat:  UPDATE
image\lib\tzmappings:  SYNCHRONIZED
image\release:  UPDATE
lib\caffeine-2.8.0.jar:  SYNCHRONIZED
lib\checker-qual-2.10.0.jar:  SYNCHRONIZED
lib\controlsfx-11.0.3.jar:  SYNCHRONIZED
lib\core-19.09-sdk2-rc.jar:  SYNCHRONIZED
lib\error_prone_annotations-2.3.3.jar:  SYNCHRONIZED
lib\fuzzywuzzy-1.2.0.jar:  SYNCHRONIZED
lib\gson-2.8.6.jar:  SYNCHRONIZED
lib\java-19.09-sdk2-rc.jar:  SYNCHRONIZED
lib\jfoenix-9.0.8.jar:  SYNCHRONIZED
lib\jna-5.5.0.jar:  SYNCHRONIZED
lib\jna-platform-5.5.0.jar:  SYNCHRONIZED
lib\json-20180813.jar:  SYNCHRONIZED
lib\jsoup-1.14.2.jar:  UPDATE
lib\just-pipe-1.0.0-SNAPSHOT.jar:  UPDATE
lib\logback-classic-1.2.3.jar:  SYNCHRONIZED
lib\logback-core-1.2.3.jar:  SYNCHRONIZED
lib\lol-client-java-api-1.2.4-20211003.201617-8.jar:  UPDATE
lib\mslinks-1.0.7-20210711.204240-3.jar:  UPDATE
lib\simple-event-bus-1.0.1-20201215.132845-3.jar:  SYNCHRONIZED
lib\slf4j-api-1.7.25.jar:  SYNCHRONIZED
lib\update4j-1.4.4.jar:  SYNCHRONIZED
open.bat:  SYNCHRONIZED
run.bat:  SYNCHRONIZED
RuneChanger.jar:  UPDATE
silent.vbs:  SYNCHRONIZED
update.bat:  SYNCHRONIZED
Downloading: image\bin\awt.dll <https://runechanger.stirante.com/stable/image/bin/awt.dll>
Downloading: image\bin\client\jvm.dll <https://runechanger.stirante.com/stable/image/bin/client/jvm.dll>
Downloading: image\bin\fontmanager.dll <https://runechanger.stirante.com/stable/image/bin/fontmanager.dll>
Downloading: image\bin\freetype.dll <https://runechanger.stirante.com/stable/image/bin/freetype.dll>
Downloading: image\bin\java.dll <https://runechanger.stirante.com/stable/image/bin/java.dll>
Downloading: image\bin\java.exe <https://runechanger.stirante.com/stable/image/bin/java.exe>
Downloading: image\bin\javajpeg.dll <https://runechanger.stirante.com/stable/image/bin/javajpeg.dll>
Downloading: image\bin\javaw.exe <https://runechanger.stirante.com/stable/image/bin/javaw.exe>
Downloading: image\bin\jawt.dll <https://runechanger.stirante.com/stable/image/bin/jawt.dll>
Downloading: image\bin\jimage.dll <https://runechanger.stirante.com/stable/image/bin/jimage.dll>
Downloading: image\bin\jli.dll <https://runechanger.stirante.com/stable/image/bin/jli.dll>
Downloading: image\bin\jrunscript.exe <https://runechanger.stirante.com/stable/image/bin/jrunscript.exe>
Downloading: image\bin\jsound.dll <https://runechanger.stirante.com/stable/image/bin/jsound.dll>
Downloading: image\bin\keytool.exe <https://runechanger.stirante.com/stable/image/bin/keytool.exe>
Downloading: image\bin\lcms.dll <https://runechanger.stirante.com/stable/image/bin/lcms.dll>
Downloading: image\bin\mlib_image.dll <https://runechanger.stirante.com/stable/image/bin/mlib_image.dll>
Downloading: image\bin\net.dll <https://runechanger.stirante.com/stable/image/bin/net.dll>
Downloading: image\bin\nio.dll <https://runechanger.stirante.com/stable/image/bin/nio.dll>
Downloading: image\bin\prefs.dll <https://runechanger.stirante.com/stable/image/bin/prefs.dll>
Downloading: image\bin\server\jvm.dll <https://runechanger.stirante.com/stable/image/bin/server/jvm.dll>
Downloading: image\bin\splashscreen.dll <https://runechanger.stirante.com/stable/image/bin/splashscreen.dll>
Downloading: image\bin\sunec.dll <https://runechanger.stirante.com/stable/image/bin/sunec.dll>
Downloading: image\bin\verify.dll <https://runechanger.stirante.com/stable/image/bin/verify.dll>
Downloading: image\bin\zip.dll <https://runechanger.stirante.com/stable/image/bin/zip.dll>
Downloading: image\conf\security\java.security <https://runechanger.stirante.com/stable/image/conf/security/java.security>
Downloading: image\legal\java.base\public_suffix.md <https://runechanger.stirante.com/stable/image/legal/java.base/public_suffix.md>
Downloading: image\legal\java.desktop\giflib.md <https://runechanger.stirante.com/stable/image/legal/java.desktop/giflib.md>
Downloading: image\legal\java.desktop\harfbuzz.md <https://runechanger.stirante.com/stable/image/legal/java.desktop/harfbuzz.md>
Downloading: image\lib\classlist <https://runechanger.stirante.com/stable/image/lib/classlist>
Downloading: image\lib\client\Xusage.txt <https://runechanger.stirante.com/stable/image/lib/client/Xusage.txt>
Downloading: image\lib\jrt-fs.jar <https://runechanger.stirante.com/stable/image/lib/jrt-fs.jar>
WARNING: Package 'jdk.internal.jimage' already exists in the boot modulepath.
        In order to prevent accidental breakage of your application among
        all your clients, the download was rejected.
        If this is only loaded on the boot *classpath* or the *business* application,
        and great caution was taken it should not be included in the boot modulepath, you may
        override this restriction by setting 'ignoreBootConflict="true"' in
        the configuration.


java.lang.IllegalStateException: Package 'jdk.internal.jimage' in module 'a3300809282971182924.tmp' conflicts with a package in the boot modulepath
        at org.update4j.ConfigImpl.checkBootConflicts(ConfigImpl.java:359)
        at org.update4j.ConfigImpl.validateFile(ConfigImpl.java:300)
        at org.update4j.ConfigImpl.doUpdate(ConfigImpl.java:165)
        at org.update4j.Configuration.update(Configuration.java:988)
        at org.update4j.Configuration.update(Configuration.java:920)
        at org.update4j.service.DefaultBootstrap.updateFirst(DefaultBootstrap.java:163)
        at org.update4j.service.DefaultBootstrap.main(DefaultBootstrap.java:103)
        at org.update4j.Bootstrap.start(Bootstrap.java:296)
        at org.update4j.Bootstrap.start(Bootstrap.java:279)
        at org.update4j.Bootstrap.start(Bootstrap.java:181)
        at org.update4j.Bootstrap.main(Bootstrap.java:112)
Exception in thread "main" java.lang.NoClassDefFoundError: com/stirante/lolclient/ClientConnectionListener
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3143)
        at java.base/java.lang.Class.getConstructor0(Class.java:3348)
        at java.base/java.lang.Class.getConstructor(Class.java:2157)
        at org.update4j.service.Service.loadService(Service.java:70)
        at org.update4j.ConfigImpl.doLaunch(ConfigImpl.java:514)
        at org.update4j.Configuration.launch(Configuration.java:1260)
        at org.update4j.service.DefaultBootstrap.updateFirst(DefaultBootstrap.java:184)
        at org.update4j.service.DefaultBootstrap.main(DefaultBootstrap.java:103)
        at org.update4j.Bootstrap.start(Bootstrap.java:296)
        at org.update4j.Bootstrap.start(Bootstrap.java:279)
        at org.update4j.Bootstrap.start(Bootstrap.java:181)
        at org.update4j.Bootstrap.main(Bootstrap.java:112)
Caused by: java.lang.ClassNotFoundException: com.stirante.lolclient.ClientConnectionListener
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 13 more
```

**(please complete the following information):**
 - OS: Windows 10
 - RuneChanger Version 1.14.1

**Comment by mordechaim** [comment]
@stirante 
My 2 cents as the update4j maintainer: this annoying error no longer happens in the most recent version of update4j. It now has a smarter check to avoid breaking the module system.

Mean while, you can safely slap the ignoreBootConflict attribute, since you load the app entirely on the class path.

**Comment by stirante** [comment]
@mordechaim sorry for tagging, but I tried to update update4j to newest version. The migration guide says about zip updates, but RuneChanger uses differential updates based on checksums. Is there anything extra I need to do to properly migrate to the newest version? 
https://github.com/stirante/RuneChanger/commit/db913f3d607379efcd78b09fa84b77197635472d

EDIT: I noticed, that old update models were depracated, why is that? I specifically chose update4j, because I don't want to force my users to download over 70mb each update

**Comment by mordechaim** [comment]
@stirante 
Zip updates still use differential updates, just instead of downloading the files directly to the target location it first bundles them into a zip file. There are a few reasons for this indirection, but the result is just the same.

Either way, the old way still works for backward compatibility. 

The issue you might face is that your clients will initially run the update with an old version of update4j, so they won't execute the new version until a subsequent run.
Since this is a very common issue, we made sure to not break anything with the new version. The configuration file stays the same.

**Comment by stirante** [comment]
@mordechaim I tried updating now with version 1.5.7 and got this error
```
Nov 17, 2021 9:02:10 PM org.update4j.util.Warning signature
WARNING: Updating without signature validation is strongly discouraged.
Exception in thread "main" java.lang.NullPointerException
        at org.update4j.service.DefaultUpdateHandler.clearln(DefaultUpdateHandler.java:153)
        at org.update4j.service.DefaultUpdateHandler.failed(DefaultUpdateHandler.java:74)
        at org.update4j.ConfigImpl.doUpdate(ConfigImpl.java:396)
        at org.update4j.Configuration.update(Configuration.java:915)
        at org.update4j.service.DefaultBootstrap.updateFirst(DefaultBootstrap.java:206)
        at org.update4j.service.DefaultBootstrap.main(DefaultBootstrap.java:147)
        at org.update4j.Bootstrap.start(Bootstrap.java:297)
        at org.update4j.Bootstrap.start(Bootstrap.java:280)
        at org.update4j.Bootstrap.start(Bootstrap.java:182)
        at org.update4j.Bootstrap.main(Bootstrap.java:113)
```

I update just by executing this
```
"updateImage/bin/java" -jar lib/update4j-1.5.7.jar --local update.xml
```

Should I make an issue?

EDIT: Ok, I found out it's probably this issue https://github.com/update4j/update4j/issues/142
Is there any workaround until this fix gets into release?

**Comment by mordechaim** [comment]
This seems to be related to https://github.com/update4j/update4j/issues/142, namely, there's underlying error and the UpdateHandler tries to print the error to the console but output stream is still null.

**Comment by mordechaim** [comment]
Can you try with this build?
[update4j-1.5.8.zip](https://github.com/stirante/RuneChanger/files/7557800/update4j-1.5.8.zip)

**Comment by stirante** [comment]
> 
> 
> Can you try with this build? [update4j-1.5.8.zip](https://github.com/stirante/RuneChanger/files/7557800/update4j-1.5.8.zip)

This build actually let me know what the issue is. After fixing the issue, older version works as well. Thanks!

@mordechaim Do you think it would be ok to use older version? Like it won't be a problem unless there is another problem

**Comment by mordechaim** [comment]
@stirante 
It's just a print issue, so you don't get the correct diagnostics. Since nothing came for so long since this was fixed, I might release it anyway with just this. Will see soon.

**Comment by stirante** [comment]
Again thanks for help, update4j has been updated and RuneChanger seems to work perfectly with it now.
